name: "CI - Test Features"
on:
  push:
    branches:
      - main
      - bugfix/**
      - feature/**
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli
      - name: Run global tests
        run: devcontainer features test --global-scenarios-only .
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli
      - name: Publish to Cloudsmith
        run: devcontainer features publish src -r docker.cloudsmith.io -n ${{ github.repository }}
        env:
          DEVCONTAINERS_OCI_AUTH: docker.cloudsmith.io:${{ secrets.CLOUDSMITH_KEY }}