name: "CI - Test Features"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli
      - name: Run global tests
        run: devcontainer features test --global-scenarios-only .